Add syntax highlighting
awslabs/smithy-intellij pull request #16
Opened 2021-05-04 15:48 UTC by srchase

This PR adds syntax highlighting for the Smithy IDL, via `Flex` and `BNF` files used to generate the Lexer and Parser classes.

Two Gradle tasks have been added. `generateSmithyParser` uses the `Smithy.bnf` file to generate the parser classes to `/src/gen/main`. `generateSmithyLexer` uses the `Smithy.flex` file to generate the lexer class to the same path.

When making changes to either file, the lexer and parser classes should be re-generated when building. For now, this is invoked manually `./gradlew generateSmithyLexer generateSmithyParser`.

For development, the `Grammar-Kit` plugin is especially useful, adding context menu options to regenerate the Lexer and Parser classes, along with a live-preview for tuning the BNF. However, the `Grammar-Kit` plugin generates slightly different generated classes due to the differences in the vended generators. As a result, only the Gradle tasks should be used for generating classes that get committed to this repository.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-05-04 15:51 UTC, srchase commented on src/main/gen/software/amazon/smithy/plugin/language/SmithyLexer.java
> +
There's an issue with the Lexer generator vended in the Grammar-Kit plugin that results in this extra space after the doc.

2021-05-04 21:31 UTC, kstich requested changes

2021-05-04 21:31 UTC, kstich commented on src/main/java/software/amazon/smithy/plugin/language/Smithy.bnf
> +//node_string_value ::= shape_id | TEXT_BLOCK | quoted_text
It looks like there are a bunch of leftover productions in comments to clean up.

2021-05-04 21:31 UTC, kstich commented on src/main/java/software/amazon/smithy/plugin/language/Smithy.bnf
> +version_section ::= VERSION COLON ws QUOTED_TEXT
If it's not feasible to make this a full `control_section` at the moment, let's leave a note here.

2021-05-04 21:31 UTC, kstich commented on src/main/java/software/amazon/smithy/plugin/language/Smithy.bnf
> +node_object_key ::= QUOTED_TEXT | IDENTIFIER
Can this be up by the other `node_object` pieces?

2021-05-04 22:46 UTC, srchase commented on build.gradle.kts
> +val generateSmithyLexer = task<GenerateLexer>("generateSmithyLexer") {
Added in ee04ca9 before compiliation.

2021-05-04 22:50 UTC, srchase commented on src/main/java/software/amazon/smithy/plugin/language/SmithySyntaxHighlighter.java
> +package software.amazon.smithy.plugin.language;
No, it is not.

2021-05-06 00:19 UTC, kstich commented on src/main/java/software/amazon/smithy/plugin/language/SmithySyntaxHighlighter.java
> +    private static final TextAttributesKey[] BAD_CHAR_KEYS = new TextAttributesKey[]{BAD_CHARACTER};
Nit: `BAD_CHAR_KEYS` is the only shortened name for these, can just keep it similar.

2021-05-06 17:13 UTC, kstich approved these changes

2021-05-06 17:15 UTC, merged